<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE8YcXu5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE8YcXu5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE8YcXu5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE8YcXu5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE8YcXu5\App_KernelDevDebugContainer([
    'container.build_hash' => 'E8YcXu5',
    'container.build_id' => '2b1b85f1',
    'container.build_time' => 1709113185,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE8YcXu5');
